//
// cesium.d.ts
//
// TypeScript definition file for Cesium
//
// This file is automatically generated by jsdoc-typescript-plugin. Do not edit this file
// unless you know what you're doing
//

declare module __Cesium {
    /**
     * Type alias for a promise
     */
    type Promise<T> = PromiseLike<T>;
    
    type TypedArray = any[];
    
    /**
     * Alias for HTML image
     */
    type Image = HTMLImageElement;
    
    /**
     * Alias for HTML canvas
     */
    type Canvas = HTMLCanvasElement;