//
// openlayers.d.ts
//
// TypeScript definition file for OpenLayers 3
//
// This file is automatically generated by jsdoc-typescript-plugin. Do not edit this file
// unless you know what you're doing
//

declare module goog {
    module events {
        class Event {
            
        }
        class EventTarget {
            
        }
    }
}