//
// openlayers.d.ts
//
// TypeScript definition file for OpenLayers 3 (v3.13.1)
//
// This file is automatically generated by jsdoc-typescript-plugin (https://github.com/jumpinjackie/jsdoc-typescript-plugin). 
//
// Do not edit this file unless you know what you're doing. Where possible, consult the plugin documentation for options to
// augment the this generated file
//

// Stubs for Closure Library types

declare module goog {
    class Disposable {
        
    }
    module events {
        class Event {
            
        }
        class EventTarget {
            
        }
    }
}