/// <reference path="../typings/tsd.d.ts" />
/**
 * @overview Generates a TypeScript definition file from assembled JSDoc doclets
 * @module plugins/typescript
 * @author Jackie Ng <jumpinjackie@gmail.com>
 */
'use strict';

var fs = require('fs');
var env = require('jsdoc/env');
var config = env.conf.typescript || {};
var moduleName = env.conf.typescript.rootModuleName || "generated";
var outDir = env.conf.typescript.outDir || ".";
var fileName = outDir + "/" + moduleName + ".d.ts";

function process(doclets) {
    var content = "/**";
    content += "\n * " + fileName
    content += "\n * ";
    content += "\n * This file was automatically generated by the typescript JSDoc plugin";
    content += "\n * Do not edit this file unless you know what you're doing";
    content += "\n */"
    
    for (var i = 0; i < doclets.length; i++) {
        var doclet = doclets[i];
        content += "\n// ==================== BEGIN " + doclet.longname + " ================= //";
        content += "\n" + JSON.stringify(doclet, null, 4);
        content += "\n// ===================== END " + doclet.longname + " ================== //\n";
    }
    
    fs.writeFile(fileName, content, function(err) {
        if (err) {
            console.log(err);
        } else {
            console.log("Saved TypeScript definition file to: " + fileName);
        }
    });
}

exports.handlers = {
    processingComplete: function(e) {
        process(e.doclets);
    }
};